# codecov options

coverage:
  status:
    project:
      default:
        informational: true
ignore:
  - "improver/cli"  # ignore folders and all its contents
  - "improver/ensemble_copula_coupling/numba_utilities.py"  # numba not installed in CI environment
