version: 2

sphinx:
  configuration: doc/source/conf.py

conda:
  environment: doc/rtd_environment.yml

# Add the current directory to the PYTHONPATH. This directory contains the 
# latest version of the IMPROVER code available when triggering the ReadTheDocs build.
python:
  install:
    - method: pip
      path: .

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_create_environment:
      # READTHEDOCS_GIT_IDENTIFIER contains the branch name for regular branch builds and tags,
      # but contains the PR number for pull request builds. Substitute BRANCH_NAME in the
      # conda environment file, trying the matching branch/PR first, falling back to master.
      - |
        if git ls-remote --heads https://github.com/metoppv/improver_example_data.git ${READTHEDOCS_GIT_IDENTIFIER} | grep -q ${READTHEDOCS_GIT_IDENTIFIER}; then
          BRANCH_NAME=${READTHEDOCS_GIT_IDENTIFIER}
        else
          BRANCH_NAME=master
        fi
        echo "Using improver_example_data branch: $BRANCH_NAME"
        sed -i "s/\${BRANCH_NAME}/${BRANCH_NAME}/g" doc/rtd_environment.yml
