version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: doc/rtd_environment.yml

# Add the current directory to the PYTHONPATH. This directory contains the 
# latest version of the IMPROVER code available when triggering the ReadTheDocs build.
python:
  install:
  - method: pip
    path: .

sphinx:
  configuration: doc/source/conf.py
