version: 2

sphinx:
  configuration: doc/source/conf.py

conda:
  environment: doc/rtd_environment.yml

# Add the current directory to the PYTHONPATH. This directory contains the 
# latest version of the IMPROVER code available when triggering the ReadTheDocs build.
python:
  install:
    - method: pip
      path: .

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_create_environment:
      # Extract the actual branch name from git
      - export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
      - echo "Detected branch name - $BRANCH_NAME"
      # Try to install improver_example_data from matching branch, fall back to main
      - pip install git+https://github.com/metoppv/improver_example_data.git@${BRANCH_NAME} || pip install git+https://github.com/metoppv/improver_example_data.git@master
