version: 2

sphinx:
  configuration: doc/source/conf.py

conda:
  environment: doc/rtd_environment.yml

# Add the current directory to the PYTHONPATH. This directory contains the 
# latest version of the IMPROVER code available when triggering the ReadTheDocs build.
python:
  install:
    - method: pip
      path: .

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_create_environment:
      # READTHEDOCS_GIT_IDENTIFIER contains the branch name for regular branch builds and tags,
      # but contains the PR number for pull request builds. Try to install improver_example_data
      # from matching branch/PR, fall back to master if not found.
      - pip install git+https://github.com/metoppv/improver_example_data.git@${READTHEDOCS_GIT_IDENTIFIER} || pip install git+https://github.com/metoppv/improver_example_data.git@master
