# This environment is intended to be used for the conda-forge improver-feedstock
# dependencies in https://github.com/conda-forge/improver-feedstock
# If this file is changed, recipe/meta.yaml in the improver-feedstock repository
# should also be updated.
# This environment should not include optional dependencies.
# This environment should pin versions so that all unit tests pass.
name: improver_conda_forge
channels:
  - conda-forge
dependencies:
  - python=3.12
  # Included in improver-feedstock requirements
  - cartopy
  - clize
  - iris=3.12
  - numpy=2.2
  - scipy=1.15
  - sphinx
  - pandas
  # Additional libraries to run tests, not included in improver-feedstock
  - filelock
  - pytest
  - setuptools
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - threadpoolctl
