# This environment is intended to be used for the conda-forge improver-feedstock
# dependencies in https://github.com/conda-forge/improver-feedstock
# If this file is changed, recipe/meta.yaml in the improver-feedstock repository
# should also be updated.
# This environment should not include optional dependencies.
# This environment should pin versions so that all unit tests pass.
name: improver_conda_forge
channels:
  - conda-forge
dependencies:
  - python=3.12
  # Included in improver-feedstock requirements
  - cartopy
  - clize
  - geopandas
  - iris=3.12
  - numpy=2.2
  - scipy=1.15
  - sphinx<9.0.0  # https://github.com/tox-dev/sphinx-autodoc-typehints/issues/586
  - pandas
  - pysteps
  # Additional libraries to run tests, not included in improver-feedstock
  - filelock
  - pytest
  - setuptools
  - sphinx-autodoc-typehints
  - sphinx-book-theme  
  - sphinx-gallery
  - threadpoolctl
  - pip
  - pip:
    - git+https://github.com/metoppv/improver_example_data.git@${BRANCH_NAME}
